#' Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AjouSelves_iOS_App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'KakaoSDKUser'
pod 'KakaoSDK'
pod 'KakaoSDKCommon'  # 필수 요소를 담은 공통 모듈
pod 'KakaoSDKAuth'  # 사용자 인증
pod 'KakaoSDKUser'  # 카카오 로그인, 사용자 관리
pod 'KakaoSDKTalk'  # 친구, 메시지(카카오톡)
pod 'KakaoSDKStory'  # 카카오스토리 
pod 'KakaoSDKLink'  # 메시지(카카오링크)
pod 'KakaoSDKTemplate'  # 메시지 템플릿 
pod 'KakaoSDKNavi'  # 카카오내비
pod 'Alamofire', '~> 5.2'

  # Pods for AjouSelves_iOS_App

end
